
CREATE DATABASE RETAILS;

USE RETAILS;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE DEMOGRAPHIC_RAM
(AGE_DESC CHAR(20),
 MARTIAL_STATUS_CODE CHAR(5),
 INCOME_DESC VARCHAR (40),
 HOMEOWNER_DESC VARCHAR(40),
 HH_COMP_DESC VARCHAR(50),
 HOUSEHOLD_SIZE_DESC VARCHAR(50),
 KID_CATEGORY_DESC VARCHAR(40),
 HOUSEHOLD_KEY INT PRIMARY KEY
 );

 CREATE OR REPLACE TABLE CAMPAIGN_DESC_RAW
 (DESCRIPTION CHAR(10),
 CAMPAIGN INT,
 START_DAY INT,
 END_DAY INT,
 PRIMARY KEY(DESCRIPTION),
 UNIQUE (CAMPAIGN)
);

CREATE OR REPLACE TABLE CAMPAIGN_RAW (
    DESCRIPTION CHAR(10),
    HOUSEHOLD_KEY INT,
    CAMPAIGN INT,
    FOREIGN KEY (DESCRIPTION) REFERENCES CAMPAIGN_DESC_RAW(DESCRIPTION),
    FOREIGN KEY (CAMPAIGN) REFERENCES CAMPAIGN_DESC_RAW(CAMPAIGN),
    FOREIGN KEY (HOUSEHOLD_KEY) REFERENCES DEMOGRAPHIC_RAM(HOUSEHOLD_KEY)
);

CREATE OR REPLACE TABLE PRODUCT_RAW(
    PRODUCT_ID INT PRIMARY KEY,
    MANUFACTURER INT,
    DEPARTMENT VARCHAR(50),
    BRAND VARCHAR(30),
    COMMODITY_DESC VARCHAR(65),
    SUB_COMMODITY_DESC VARCHAR(65),
    CURR_SIZE_OF_PRODUCT VARCHAR(15)
);

CREATE OR REPLACE TABLE COUPON_REDEMPT_RAW
(HOUSEHOLD_KEY	INT,
DAY	INT,
COUPON_UPC	INT,
CAMPAIGN INT,
FOREIGN KEY (HOUSEHOLD_KEY) REFERENCES DEMOGRAPHIC_RAM(HOUSEHOLD_KEY),
FOREIGN KEY (CAMPAIGN) REFERENCES CAMPAIGN_DESC_RAW(CAMPAIGN)
);

CREATE OR REPLACE TABLE COUPON_RAW(
    COUPON_UPC INT,
    PRODUCT_ID INT,
    CAMPAIGN INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_RAW(PRODUCT_ID),
    FOREIGN KEY (CAMPAIGN) REFERENCES CAMPAIGN_DESC_RAW(CAMPAIGN)
);

CREATE OR REPLACE TABLE TRANSACTION_RAW(
    HOUSEHOLD_KEY INT,
    BASKET_ID INT,
    DAY INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    SALES_VALUE FLOAT,
    STORE_ID INT,
    RETAIL_DISC FLOAT,
    TRANS_TIME INT,
    WEEK_NO INT,
    COUPON_DISC INT,
    COUPON_MATCH_DISC INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_RAW(PRODUCT_ID),
    FOREIGN KEY (HOUSEHOLD_KEY) REFERENCES DEMOGRAPHIC_RAM(HOUSEHOLD_KEY)
);

CREATE OR REPLACE FILE FORMAT RETAIL_CSV
    TYPE='CSV'
    COMPRESSION = 'NONE'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE'
    SKIP_HEADER = 1;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::211125783493:role/myretailrole'
STORAGE_ALLOWED_LOCATIONS = ('S3://retailrawcomp/');

DESC INTEGRATION S3_INT;

CREATE OR REPLACE STAGE RETAIL_STAGE
URL = 'S3://retailrawcomp'
FILE_FORMAT = RETAIL_CSV
STORAGE_INTEGRATION = S3_INT;

LIST @RETAIL_STAGE;

SHOW STAGES;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_CAMPAIGN_DESC_RAW AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.CAMPAIGN_DESC_RAW
FROM '@RETAIL_STAGE/CAMPAIGN_DESC'
FILE_FORMAT = RETAIL_CSV;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_CAMPAIGN_RAW AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.CAMPAIGN_RAW
FROM '@RETAIL_STAGE/CAMPAIGN'
FILE_FORMAT = RETAIL_CSV;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_COUPON_REDEMPT_RAW AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.COUPON_REDEMPT_RAW
FROM '@RETAIL_STAGE/COUPON_REDEMPT'
FILE_FORMAT = RETAIL_CSV;


CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_COUPON AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.COUPON_RAW
FROM '@RETAIL_STAGE/COUPON'
FILE_FORMAT = RETAIL_CSV;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_DEMOGRAPHIC_RAW AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.DEMOGRAPHIC_RAM
FROM '@RETAIL_STAGE/DEMOGRAPHIC'
FILE_FORMAT = RETAIL_CSV;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_PRODUCT_RAW AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.PRODUCT_RAW
FROM '@RETAIL_STAGE/PRODUCT'
FILE_FORMAT = RETAIL_CSV;

CREATE OR REPLACE PIPE RETAIL_SNOWPIPE_TRANSACTION_RAW AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.TRANSACTION_RAW
FROM '@RETAIL_STAGE/TRANSACTION'
FILE_FORMAT = RETAIL_CSV;

SHOW PIPES;


ALTER PIPE RETAIL_SNOWPIPE_CAMPAIGN_DESC_RAW REFRESH;
SELECT COUNT(*) FROM RETAILS.PUBLIC.CAMPAIGN_DESC_RAW;

ALTER PIPE RETAIL_SNOWPIPE_CAMPAIGN_RAW REFRESH;
SELECT COUNT(*) FROM RETAILS.PUBLIC.CAMPAIGN_RAW;

ALTER PIPE RETAIL_SNOWPIPE_COUPON REFRESH;
SELECT COUNT(*) FROM RETAILS.PUBLIC.COUPON_RAW;

ALTER PIPE RETAIL_SNOWPIPE_COUPON_REDEMPT_RAW REFRESH;
SELECT COUNT(*) FROM RETAILS.PUBLIC.COUPON_REDEMPT_RAW;

ALTER PIPE RETAIL_SNOWPIPE_DEMOGRAPHIC_RAW REFRESH;
SELECT COUNT(*) FROM RETAILS.PUBLIC.DEMOGRAPHIC_RAM;

ALTER PIPE RETAIL_SNOWPIPE_PRODUCT_RAW REFRESH;
SELECT COUNT(*) FROM RETAILS.PUBLIC.PRODUCT_RAW;

ALTER PIPE RETAIL_SNOWPIPE_TRANSACTION_RAW REFRESH;
SELECT COUNT(*) FROM RETAILS.PUBLIC.TRANSACTION_RAW;


SELECT SYSTEM$PIPE_STATUS('RETAIL_SNOWPIPE_TRANSACTION_RAW');

SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(TABLE_NAME=>'RETAILS.PUBLIC.TRANSACTION_RAW',
START_TIME=>DATEADD(HOURS,-1,CURRENT_TIMESTAMP())));








 